# Generated by Django 5.1.5 on 2025-02-01 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['ip_address'], name='content_rat_ip_addr_dfcb08_idx'),
        ),
    ]
